# Generated by Django 4.2.4 on 2023-08-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_being_delivered_order_recived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=250)),
            ],
        ),
    ]
